using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._PS.CargoStorage.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoStorageCartProductRow : PanelContainer
{
    public EntityPrototype Prototype;
    public CargoStorageCartProductRow(EntityPrototype prototype)
    {
        RobustXamlLoader.Load(this);
        Prototype = prototype;
    }
}
