using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Client.UserInterface.Controls;
using Content.Shared._PS.Terradrop;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class TerradropConsoleMenu : FancyWindow
{
    /// <summary>
    /// Action invoked when starting a terradrop. Passes the map ID and selected level.
    /// </summary>
    public Action<string, int>? OnStartTerradropPressed;

    /// <summary>
    /// Action invoked when disconnect is pressed.
    /// </summary>
    public Action? OnDisconnectPressed;

    /// <summary>
    /// Action invoked when reconnect is requested. Passes (mapId, instanceIndex).
    /// </summary>
    public Action<string, int>? OnReconnectPressed;

    [Dependency] private IEntityManager _entity = default!;
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly SpriteSystem _sprite;

    public EntityUid Entity;
    public ProtoId<TerradropMapPrototype>? CurrentMapNode;
    public Dictionary<string, TerradropMapAvailability> List = new();

    /// <summary>
    /// Active instance names per map ID. Updated from server state.
    /// </summary>
    public Dictionary<string, List<string>> ActiveInstances = new();

    /// <summary>
    /// Highest completed level per map ID. Updated from server state.
    /// </summary>
    public Dictionary<string, int> HighestCompletedLevels = new();

    /// <summary>
    /// The global max level for the level selector. Updated from server state.
    /// </summary>
    public int GlobalMaxLevel;

    /// <summary>
    /// The currently selected level. Remembered locally across map selections.
    /// </summary>
    private int _selectedLevel;

    private TerradropMapRow? _expandedRow;
    private readonly Dictionary<string, TerradropMapRow> _rows = new();

    public TerradropConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entity.System<SpriteSystem>();

        UpdatePanels(List);
    }

    public void UpdatePanels(Dictionary<string, TerradropMapAvailability> dict)
    {
        MapListContainer.RemoveAllChildren();
        _rows.Clear();
        _expandedRow = null;
        List = dict;

        // Group maps by tier (Position.Y), then sort by Position.X within each tier
        var grouped = dict
            .Select(kvp => (Proto: _prototype.Index<TerradropMapPrototype>(kvp.Key), Availability: kvp.Value))
            .GroupBy(x => x.Proto.Position.Y)
            .OrderBy(g => g.Key)
            .ToList();

        var first = true;
        foreach (var tier in grouped)
        {
            if (!first)
            {
                var separator = new HSeparator();
                separator.Margin = new Thickness(8, 2, 8, 2);
                separator.AddStyleClass("LowDivider");
                MapListContainer.AddChild(separator);
            }
            first = false;

            foreach (var (proto, availability) in tier.OrderBy(x => x.Proto.Position.X))
            {
                ActiveInstances.TryGetValue(proto.ID, out var instances);
                HighestCompletedLevels.TryGetValue(proto.ID, out var highestLevel);
                var row = new TerradropMapRow(proto, availability, _sprite, _selectedLevel, instances, highestLevel, GlobalMaxLevel);
                WireRowEvents(row);
                _rows[proto.ID] = row;
                MapListContainer.AddChild(row);
            }
        }

        // Auto-expand: restore previous selection or pick default
        if (CurrentMapNode != null && _rows.TryGetValue(CurrentMapNode, out var selectedRow))
        {
            ExpandRow(selectedRow);
        }
        else
        {
            var defaultProto = _prototype.EnumeratePrototypes<TerradropMapPrototype>()
                .FirstOrDefault(x => x.UnlockedByDefault);
            if (defaultProto != null && _rows.TryGetValue(defaultProto.ID, out var defaultRow))
            {
                ExpandRow(defaultRow);
            }
        }
    }

    /// <summary>
    /// Refresh active instance state on all rows without rebuilding.
    /// Called when ActiveInstances changes but MapNodes did not.
    /// </summary>
    public void UpdateInformationPanel()
    {
        foreach (var (id, row) in _rows)
        {
            ActiveInstances.TryGetValue(id, out var instances);
            row.UpdateActiveInstances(instances);
        }
    }

    private void WireRowEvents(TerradropMapRow row)
    {
        row.OnHeaderPressed += OnRowHeaderPressed;
        row.StartAction += (proto, level) => OnStartTerradropPressed?.Invoke(proto.ID, level);
        row.LevelChanged += level => _selectedLevel = level;
        row.DisconnectAction += () => OnDisconnectPressed?.Invoke();
        row.ReconnectAction += (mapId, idx) => OnReconnectPressed?.Invoke(mapId, idx);
    }

    private void OnRowHeaderPressed(TerradropMapRow row)
    {
        if (_expandedRow == row)
        {
            // Toggle off
            row.IsExpanded = false;
            _expandedRow = null;
            CurrentMapNode = null;
            return;
        }

        ExpandRow(row);
    }

    private void ExpandRow(TerradropMapRow row)
    {
        // Collapse previous
        if (_expandedRow != null)
            _expandedRow.IsExpanded = false;

        // Sync level and max to the newly expanded row
        row.UpdateMaxLevel(GlobalMaxLevel);
        row.UpdateLevel(_selectedLevel);
        row.IsExpanded = true;
        _expandedRow = row;
        CurrentMapNode = row.Prototype.ID;
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public override void Close()
    {
        base.Close();
        MapListContainer.RemoveAllChildren();
        _rows.Clear();
        _expandedRow = null;
    }
}
