using System.Linq;
using Content.Shared._PS.Terradrop;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class TerradropMapRow : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public Action<TerradropMapPrototype, int>? StartAction;
    public Action<int>? LevelChanged;
    public Action? DisconnectAction;
    public Action<string, int>? ReconnectAction;
    public Action<TerradropMapRow>? OnHeaderPressed;

    public readonly TerradropMapPrototype Prototype;
    public readonly TerradropMapAvailability Availability;

    private int _level;
    private readonly int _minLevel;
    private int _maxLevel;
    private List<string>? _activeInstances;
    private bool _isExpanded;

    public bool IsExpanded
    {
        get => _isExpanded;
        set
        {
            _isExpanded = value;
            BodyContainer.Visible = value;
            ChevronLabel.Text = value ? "▼" : "►";
        }
    }

    public TerradropMapRow(
        TerradropMapPrototype proto,
        TerradropMapAvailability availability,
        SpriteSystem sprite,
        int initialLevel = 0,
        List<string>? activeInstances = null,
        int highestCompletedLevel = 0,
        int globalMaxLevel = 0)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Prototype = proto;
        Availability = availability;
        _activeInstances = activeInstances;
        _minLevel = proto.MinLevel;
        _maxLevel = globalMaxLevel;
        _level = Math.Clamp(initialLevel, _minLevel, Math.Max(_minLevel, _maxLevel));

        var terradrop = _ent.System<TerradropSystem>();

        // Header
        NodeIcon.SetPrototype(proto.Icon);
        MapNameLabel.Text = Loc.GetString(proto.Name);

        // Status badge with color
        var colors = TerradropColorScheme.GetMapItemColors(availability);
        StatusBadge.Text = availability switch
        {
            TerradropMapAvailability.Unexplored => Loc.GetString("terradrop-row-status-unexplored"),
            TerradropMapAvailability.InProgress => Loc.GetString("terradrop-row-status-in-progress"),
            TerradropMapAvailability.Explored => Loc.GetString("terradrop-row-status-completed", ("level", highestCompletedLevel)),
            _ => Loc.GetString("terradrop-row-status-unavailable")
        };
        StatusBadge.FontColorOverride = colors.InfoText;

        // Level is shown in the badge for completed maps, so hide the redundant label.
        HighestLevelLabel.Text = "";

        // Header click
        HeaderButton.OnPressed += _ => OnHeaderPressed?.Invoke(this);

        // Body - status description
        StatusDescription.Text = Loc.GetString(availability switch
        {
            TerradropMapAvailability.Unexplored => "terradrop-availability-unexplored",
            TerradropMapAvailability.Unavailable => "terradrop-availability-unavailable",
            TerradropMapAvailability.InProgress => "terradrop-availability-in-progress",
            TerradropMapAvailability.Explored => "terradrop-availability-explored",
            _ => "terradrop-availability-unknown"
        });

        // Level controls
        InitializeLevelControls();

        // Start button text varies by availability
        StartButton.Text = Loc.GetString(availability switch
        {
            TerradropMapAvailability.Unavailable => "terradrop-start-unavailable",
            TerradropMapAvailability.InProgress => "terradrop-start-in-progress",
            TerradropMapAvailability.Explored => "terradrop-start-explored",
            _ => "terradrop-start-generic"
        });
        StartButton.Disabled = availability == TerradropMapAvailability.Unavailable;
        StartButton.OnPressed += _ => StartAction?.Invoke(Prototype, _level);

        // Disconnect/Reconnect
        UpdateInstanceButtons();
        DisconnectButton.OnPressed += _ => DisconnectAction?.Invoke();
        ReconnectButton.OnPressed += _ => HandleReconnect();

        // Prerequisites & unlocks
        InitializePrerequisites(proto, terradrop, sprite);
        InitializeMapUnlocks(proto, terradrop, sprite);
    }

    public void UpdateLevel(int level)
    {
        _level = Math.Clamp(level, _minLevel, Math.Max(_minLevel, _maxLevel));
        UpdateLevelDisplay();
    }

    public void UpdateMaxLevel(int maxLevel)
    {
        _maxLevel = maxLevel;
        _level = Math.Clamp(_level, _minLevel, Math.Max(_minLevel, _maxLevel));
        UpdateLevelDisplay();
    }

    public void UpdateActiveInstances(List<string>? instances)
    {
        _activeInstances = instances;
        UpdateInstanceButtons();
    }

    private void UpdateInstanceButtons()
    {
        var hasInstances = _activeInstances != null && _activeInstances.Count > 0;
        DisconnectButton.Visible = hasInstances;
        ReconnectButton.Visible = hasInstances;
    }

    private void HandleReconnect()
    {
        if (_activeInstances == null || _activeInstances.Count == 0)
            return;

        if (_activeInstances.Count == 1)
        {
            ReconnectAction?.Invoke(Prototype.ID, 0);
            return;
        }

        var popup = new TerradropInstanceListPopup(_activeInstances);
        popup.InstanceSelected += index => ReconnectAction?.Invoke(Prototype.ID, index);
        popup.OpenCentered();
    }

    private void InitializeLevelControls()
    {
        UpdateLevelDisplay();
        LevelMinusTenButton.OnPressed += _ => AdjustLevel(-10);
        LevelMinusButton.OnPressed += _ => AdjustLevel(-1);
        LevelPlusButton.OnPressed += _ => AdjustLevel(1);
        LevelPlusTenButton.OnPressed += _ => AdjustLevel(10);
    }

    private void AdjustLevel(int delta)
    {
        var newLevel = Math.Clamp(_level + delta, _minLevel, Math.Max(_minLevel, _maxLevel));
        if (newLevel != _level)
        {
            _level = newLevel;
            UpdateLevelDisplay();
            LevelChanged?.Invoke(_level);
        }
    }

    private void UpdateLevelDisplay()
    {
        LevelLabel.Text = _level.ToString();
        LevelBonusLabel.Text = _level > 0
            ? Loc.GetString("terradrop-level-bonus", ("bonus", _level))
            : "";
        LevelMinusButton.Disabled = _level <= _minLevel;
        LevelMinusTenButton.Disabled = _level <= _minLevel;
        LevelPlusButton.Disabled = _level >= _maxLevel;
        LevelPlusTenButton.Disabled = _level >= _maxLevel;
    }

    private void InitializePrerequisites(TerradropMapPrototype proto, TerradropSystem terradrop, SpriteSystem sprite)
    {
        foreach (var child in RequiredTechContainer.Children.ToList())
        {
            if (child != NoPrereqLabel)
                RequiredTechContainer.RemoveChild(child);
        }

        NoPrereqLabel.Visible = proto.MapPrerequisites.Count == 0 && proto.MinUnlockLevel == 0;

        if (proto.MinUnlockLevel > 0)
        {
            RequiredTechContainer.AddChild(new Label
            {
                Text = Loc.GetString("terradrop-console-prereq-level", ("level", proto.MinUnlockLevel))
            });
        }

        foreach (var mapId in proto.MapPrerequisites)
        {
            var tech = _proto.Index(mapId);
            var description = terradrop.GetMapDescription(tech);
            RequiredTechContainer.AddChild(new MiniMapCardControl(tech, description));
        }
    }

    private void InitializeMapUnlocks(TerradropMapPrototype proto, TerradropSystem terradrop, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var mapId in proto.MapUnlocks)
        {
            var map = _proto.Index(mapId);
            var description = terradrop.GetMapDescription(map);
            UnlocksContainer.AddChild(new MiniMapCardControl(map, description));
        }
    }
}
