using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class TerradropConsoleMenu : FancyWindow
{
    public event Action<BaseButton.ButtonEventArgs>? OnStartButtonPressed;

    public TerradropConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartTerradropButton.OnPressed += args => OnStartButtonPressed?.Invoke(args);
    }
}
